services:
    _defaults:
        autowire: true
        autoconfigure: true

    Naoned\OaiPmhServerBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Naoned\OaiPmhServerBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Naoned\OaiPmhServerBundle\Controller\MainController:
        arguments:
            $oDataProvider: '@naoned.oaipmh.data_provider'

    Naoned\OaiPmhServerBundle\Twig\RecordExtension:
        arguments:
            $oDataProvider: '@naoned.oaipmh.data_provider'
